name: Platform.SystemContext CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/dotnet-build-template.yml@main
    with:
      project_path: 'Platform.SystemContext.csproj'


